### ISSUE TITLE
Conversion to Jekyll

### ISSUE THREAD

**Issue by captn3m0** [sdslabs/jee#3]
Our JEE website needs to be _jekyll-ized_ so that we can easily maintain it in the future. Some points to be considered: 
1. Create 2 layouts, one for the 2013, and another for 2012 results
2. Both layouts should include the top header links and bottom credits at footer
3. Convert all html files to markdown files. Use markdown inline images, if there is scope
4. You'd need to install jekyll gem , which means u will have to install ruby
5. use rvm for installing ruby. Pick v1.9.3 
6. pandoc might be of some help to you
7. Remove the _site folder using gitignore
8. You can include css/js files inside the markdown files.
9. There is something called "include" in jekyll, which can be used to include complete files inline. Take a look at it, and use it in some cases (for eg keep disclaimer text in disclaimer.txt and include it in both 2012 and 2013 disclaimer.md)

Do all this in another branch, which anyone can checkout and build.

**Comment by abhshkdz** [comment]
Let's just shift everything to the same theme while we're at it.

**Comment by captn3m0** [comment]
But the 2012 stuff has to link to 2012 graphs and such. Keeping a link to ./graph/ should work. (Checked that it was the only custom link in there) Another idea: Keep the fb stuff in an include file, which we can include wherever we need it.

**Comment by captn3m0** [comment]
Deadline: 5th July 2013.

**Comment by captn3m0** [comment]
See https://github.com/ruby/www.ruby-lang.org for a sample heavy website in jekyll
